{% set name = "truststore" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/truststore-{{ version }}.tar.gz
  sha256: dc70da89634944a579bfeec70a7a4523c53ffdb3cf52d1bb4a431fda278ddb96

build:
  skip: True  # [py<310]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - flit-core >=3.2,<4
    - pip
    - wheel
  run:
    - python

test:
  imports:
    - truststore
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/sethmlarson/truststore
  summary: Verify certificates using native system trust stores
  description: |
    A library which exposes native system certificate stores (ie “trust stores”)
    through an ssl.SSLContext-like API. This means that Python applications no
    longer need to rely on certifi as a root certificate store.
  dev_url: https://github.com/sethmlarson/truststore
  doc_url: https://truststore.readthedocs.io/
  license: MIT
  license_file: LICENSE
  license_family: MIT

extra:
  recipe-maintainers:
    - wolfv
