{% set name = "truststore" %}
{% set version = "0.10.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/sethmlarson/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  fn: {{ name }}-{{ version }}.tar.gz
  sha256: a470d2763875f9b9a148d5726af330d15b65d2a83f70610c262de8888ee94b4e

build:
  skip: True  # [py<310]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - flit-core >=3.2,<4
    - pip
  run:
    - python

test:
  requires:
    - pip
    - pytest
  imports:
    - truststore
  commands:
    - pip check
    # Run basic tests that don't involve complex certificate validation
    - pytest tests/test_sslcontext.py -v -k "test_create or test_options or test_protocol"  # [not (linux and s390x)]

about:
  home: https://github.com/sethmlarson/truststore
  summary: Verify certificates using native system trust stores
  description: |
    A library which exposes native system certificate stores (ie "trust stores")
    through an ssl.SSLContext-like API. This means that Python applications no
    longer need to rely on certifi as a root certificate store.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://truststore.readthedocs.io/
  dev_url: https://github.com/sethmlarson/truststore

extra:
  recipe-maintainers:
    - conda-forge/truststore
